apiVersion: apps/v1
kind: Deployment
metadata:
  name: sava-cart
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  template:
    spec:
      containers:
      - name: sava-cart
        image: vampio/sava-cart:latest
        ports:
        - name: http
          containerPort: 3000
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        envFrom:
        - configMapRef:
            name: sava-cart-configmap